---
title: "DATA 609 - Final Project"
author: "Daina Bouquin, Christophe Hunt, Christina Taylor"
date: "April 16, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
always_allow_html: yes
---

## Textbook Part III:

### The problem

The digestive processes of sheep can highlight the nutrionaly value in varied feeding schedules or varied food prepation. This is esspecially important when raising sheep for commercial purposes. 

### The digestive process

Sheep are a cud-chewing animal which means that unchewed food goes through a series of storage stomachs called the rumen and the reticulum. The process is illustrated below: 

\begin{tikzpicture}[node distance = 2cm]
  \tikzstyle{process} = [rectangle, minimum width=3cm, minimum height=1cm, text centered, draw=black, fill=orange!30]
  \tikzstyle{arrow} = [thick,->,>=stealth]
  \node (r) [process, xshift=2cm] {Rumen};
  \node (a) [process, right of=r, xshift=2cm] {Abomasum};
  \node (d) [process, right of=a, xshift=2cm] {Duodemum};
  \node (f) [process, right of=d, xshift=2cm]  {Feces};
  \draw [arrow] (r) -- (a);
  \draw [arrow] (a) -- (d);
  \draw [arrow] (d) -- (f);
\end{tikzpicture}

### The experiment

The digestive process is most observable at the beginning and at the end, we can observer and control what goes in and what comes out. 

### The model 

Suppose that at $t = 0$ a sheep is fed an amount $R$ of food which goes immediately into its rumen. This food will pass gradually from the rumen through the abomasum into the duodenum. At any later time $t$ we shall define:

$r(t)$ = the amount of food still in the rumen;
$a(t)$ = the amount in the abomasum;
$d(t)$ = the amount which by then has arrived in the duodenum.

So $r(0) = R$, $a(0)$ = $d(0)$ = 0, and, for all t>0, 
(1) $r(t) + a(t) + d(t) = R.$

### The assumptions

Two assumptions are made:
(A) Food moves out of the rumen at a rate proportional to the amount of food in the rumen. Mathematically this says:

(2) $r'(t) = -k_1r(t)$    

where k_1 is a positive proportionality constant.

(B) Food moves out of the abomasum at a rate proportional to the amout of food in the abomasum. Since at the same time food is moving into the abomasum at the rate given by Equation (2), the assumption says
(3) $a'(t) = k_1r(t)-k_2a(t)$

where k_2 is another positive proprtionality constant.

### The solutions of the equations

#### Solving for $r(t)$

It is straightforward to solve Equation (2) for $r(t)$. We just divide through by $r(t)$ and then integrate from 0 to t:

$\int_0^t \frac{r'(t)}{r(t)} dt= - \int_0^t k_1dt$    
$ln(\frac{r(t)}{R}) = -k_1t$,
since r(0) = R, and finally
(4) $r(t) = Re^{-k_1t}$ 

#### Solving for $a(t)$

Finding $a(t)$ is a bit more tricky. Applying Equations (4) to Equation (3) we get:

(5) $a'(t) = k_1Re^{-k_1t}-k_2a(t)$

Equation (5) probably looks quite different from any you have seen before. Let us try to make a shrew quess what kind of solution it has. It says that the derivative of $a(t)$ is the sume of two terms, $k_1Re^{-k_1t}$ and $-k_2a(t)$. With luck, this might remind us of the product rule:

(6) if $a(t) = u(t) \bullet v(t)$
    then $a'(t) = u(t) \bullet v'(t) + v(t) \bullet u'(t)$
    
Can we pick $u(t)$ and $v(t)$ so the terms in Equation (6) match up with the terms in Equation (5)? In other words, can we pick $u(t)$ and $v(t)$ so that 

(7) $u(t) \bullet v'(t) = k_1Re^{-k_1^t}$

and 

(8) $v(t) \bullet u'(t) = -k_2a(t)?$

Since $a(t) = u(t) \bullet v(t)$, Equation (8) can rewritten 
$v(t) \bullet u'(t) = -k_2u(t)v(t)$, we are in business! The $v(t)$ factors cancel out, leaving us with 

$$u'(t) = -k_2u(t)$$

which looks very much like Equation (2) and can be solved in the same way. 


$\int_0^t \frac{u'(t)}{u(t)} dt = -\int_0^t k_2dt$

Writing K = u(0):

$ln (\frac{u(t)}{K}) = -k_2t$    
$u(t) = Ke^{-k_2t}$.   

Putting this into Equation (7) gives

$Ke^{-k_2t}v'(t) = k_1Re^{-k_1t}$    
$v'(t) = \frac{k_1R}{K}e(k_2-k_1)^t$.

If $k_1 = k_2$ we feel confident you can complete this solution yourself (Exercise 1). 

#TODO Complete this exercise

Exercise 1. Find $a(t)$ if $k_1 = k_2$. 

If $k_1 \neq k_2$, then $k_2 - k _1 \neq 0$ and so we can write 

$$v(t) = \frac{k_1R}{K(k_2 - k_1)}e^(k_2 -k_1)^t +c$$

Where C is the constant of integratoin. Then

$$a(t) = u(t) \bullet v(t) = \frac{k_1R}{k_2-k_1}e^{-k_1t} + CKe^{-k_2t}$$



